swagger: '2.0'
info:
  description: Product service Api
  version: 1.0.0
  title: Product Service API
  contact:
    email: aliaksandr_varachai@epam.com
  license:
    name: ISC
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers

paths:
  /products:
    get:
      tags:
      - developers
      summary: Gets products list
      operationId: getProductsList
      description: Provides products list
      produces:
        - application/json
      responses:
        200:
          description: products list
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductItem'
        500:
          description: Server error
    post:
      tags:
        - developers
      summary: Adds a product
      operationId: createProduct
      description: Creates a new product
      consumes: 
      - application/json
      parameters:
        - in: body
          name: createProductId
          description: ID of a product
          schema:
            type: object
            required:
              - title
              - price
              - count
            properties:
              title:
                type: string
              description:
                type: string
              price:
                type: integer
              count:
                type: integer
      produces:
        - application/json
      responses:
        200:
          description: Product is created
        400:
          description: Wrond data schema
        500:
          description: Server error
  /products/{productId}:
    get:
      tags:
      - admins
      summary: Gets a product by ID
      operationId: getProductsById
      description: Provides products list
      parameters:
      - in: path
        name: productId
        description: ID of a product
        required: true
        type: string
        format: uuid
      produces:
      - application/json
      responses:
        200:
          description: product is found
        500:
          description: Server error
definitions:
  ProductItem:
    type: object
    required:
    - id
    - description
    - count
    - price
    - title
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      description:
        type: string
        example: Widget Adapter
      count:
        type: integer
        minimum: 0
        maximum: 1000
        example: 42
      price:
        type: number
        minimum: 0
        example: 5.99
      title:
        type: string
        example: Some text description  
host: virtserver.swaggerhub.com
basePath: /AliaksandrVarachai/product-service/1.0.0
schemes:
 - https